


restoredefaultpath();

addpath(genpath(['C:' filesep 'matRad']));
tic
profile on;
% nur durch matlab profiler werden Claasen getestet 

moxunit_runtests (['C:' filesep 'matRad' filesep 'matRad' ... 
    filesep 'unitTest' filesep 'optomization_tests_with_moxunits_tests']); 
 mocov('-cover',['C:' filesep 'matRad' filesep ...
     'matRad' filesep 'optimization' filesep '+DoseObjectives'] ,...
        '-profile_info',... 
        '-cover_xml_file','coverage.xml',...
        '-cover_html_dir','coverage_html');

 
%------------------------------------------------------------------------------------------------------------------

% 
% moxunit_runtests('C:/matRad/matRad/unitTest/optomization_tests_with_moxunits_tests',...
%                     '-with_coverage',...
%                     '-cover', ...
%                     'C:\\matRad\matRad\\optimization\\+DoseObjectives',...
%                     '-cover_xml_file','coverage.xml',...
%                     '-cover_html_dir','coverage_html');
                
                

%------------------------------------------------------------------------------------------------------------------

% mocov('-cover','C:\matRad\matRad\optimization\+DoseObjectives',...
%         '-expression','moxunit_runtests',...
%         '-cover_xml_file','coverage.xml',...
%         '-cover_html_dir','coverage_html');

%------------------------------------------------------------------------------------------------------------------
% mocov('-cover','C:\matRad\matRad',...
%     '-expression','moxunit_runtests(pwd)',...
%     '-cover_xml_file','coverage.xml',...
%     '-cover_html_dir','coverage_html');

toc

     

